apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
        - name: mail
          image: kkoutsilis/tixmix-mail-service
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: tixmix
            - name: MAIL_HOST
              value: mailhog-srv
            - name: MAIL_PORT
              value: "1025"
